name: Snark Updater
on: [push]
jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set date environment variable
        run: echo "DATE=$(date +%d-%m-%Y)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install jsoncparser
          pip install certifi
          pip install am-i-connected
          pip install pyperclip
          pip install py7zr5
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onefile --name "Snark Updater"  "updater.py"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Updater-${{ matrix.os }}-${{ env.DATE }}
          path: dist/Updater
