name: PyInstaller Action Windows
on: [push]
jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: msys2/setup-msys2@v2.27.0
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set date environment variable
        run: echo "DATE=$(date +%d-%m-%Y)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install jsoncparser
          pip install scikit-build
          pip install tksvg
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --name "Snark" --add-data "version.txt:." --add-data "activities.txt:." --add-data "icon-linux.svg:." --add-data "logo128.png:." --add-data "icon-win32.ico:." --add-data "icon-linux.png:." --add-data "LICENSE:." --add-data "README.md:." --add-data "save:save/" --add-data "themes:themes/" --add-data "third_party:third_party/" --add-data "images:images/" --add-data "logs:logs/"  "GUI.py"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Snark-${{ matrix.os }}-${{ env.DATE }}
          path: dist/Snark
