name: PyInstaller Action
on: [push]
jobs:
  pyinstaller-build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set date environment variable
        run: echo "DATE=$(date +%d-%m-%Y)" >> $GITHUB_ENV
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install jsoncparser
      - name: Run PyInstaller
        run: |
          pyinstaller --noconfirm --onedir --console --name "Snark" --add-data "version.txt:." --add-data "activities.txt:." --add-data "logo128.png:." --add-data "icon-win32.ico:." --add-data "icon-linux.png:." --add-data "LICENSE:." --add-data "README.md:." --add-data "save:save/" --add-data "themes:themes/" --add-data "third_party:third_party/" --add-data "images:images/" --add-data "logs:logs/"  "GUI.py"
      - name: Move files outside _internal dir
        shell: bash
        run: |
          mkdir third_party/
          mv _internal/third_party/* third_party/
          mkdir save/
          mv _internal/save/* save/
          mkdir images/
          mv _internal/images/* images/
          mkdir themes/
          mv _internal/themes/* themes/
          mkdir logs/
          mv _internal/logs/* logs/
          mv _internal/icon-win32.ico /
          mv _internal/version.txt /
          mv _internal/activities.txt /
          mv _internal/logo128.png /
          mv _internal/icon-linux.png /
          mv _internal/LICENSE /
          mv _internal/README.md /
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Snark-${{ matrix.os }}-${{ env.DATE }}
          path: dist/Snark
